// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: celestia/signing/v1/types.proto

package signing

import (
	fmt "fmt"
	privval "github.com/cometbft/cometbft/proto/tendermint/privval"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// SignP2PMessageRequest asks a kms system to sign a hash.
type SignP2PMessageRequest struct {
	Hash     []byte `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	ChainId  string `protobuf:"bytes,2,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	UniqueId string `protobuf:"bytes,3,opt,name=unique_id,json=uniqueId,proto3" json:"unique_id,omitempty"`
}

func (m *SignP2PMessageRequest) Reset()         { *m = SignP2PMessageRequest{} }
func (m *SignP2PMessageRequest) String() string { return proto.CompactTextString(m) }
func (*SignP2PMessageRequest) ProtoMessage()    {}
func (*SignP2PMessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1a43d868e18fb998, []int{0}
}
func (m *SignP2PMessageRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SignP2PMessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SignP2PMessageRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SignP2PMessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignP2PMessageRequest.Merge(m, src)
}
func (m *SignP2PMessageRequest) XXX_Size() int {
	return m.Size()
}
func (m *SignP2PMessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignP2PMessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SignP2PMessageRequest proto.InternalMessageInfo

func (m *SignP2PMessageRequest) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *SignP2PMessageRequest) GetChainId() string {
	if m != nil {
		return m.ChainId
	}
	return ""
}

func (m *SignP2PMessageRequest) GetUniqueId() string {
	if m != nil {
		return m.UniqueId
	}
	return ""
}

// SignedP2PMessageResponse returns the signature from the kms.
type SignedP2PMessageResponse struct {
	Signature []byte                     `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	Error     *privval.RemoteSignerError `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (m *SignedP2PMessageResponse) Reset()         { *m = SignedP2PMessageResponse{} }
func (m *SignedP2PMessageResponse) String() string { return proto.CompactTextString(m) }
func (*SignedP2PMessageResponse) ProtoMessage()    {}
func (*SignedP2PMessageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1a43d868e18fb998, []int{1}
}
func (m *SignedP2PMessageResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SignedP2PMessageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SignedP2PMessageResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SignedP2PMessageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignedP2PMessageResponse.Merge(m, src)
}
func (m *SignedP2PMessageResponse) XXX_Size() int {
	return m.Size()
}
func (m *SignedP2PMessageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SignedP2PMessageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SignedP2PMessageResponse proto.InternalMessageInfo

func (m *SignedP2PMessageResponse) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *SignedP2PMessageResponse) GetError() *privval.RemoteSignerError {
	if m != nil {
		return m.Error
	}
	return nil
}

func init() {
	proto.RegisterType((*SignP2PMessageRequest)(nil), "celestia.signing.v1.SignP2PMessageRequest")
	proto.RegisterType((*SignedP2PMessageResponse)(nil), "celestia.signing.v1.SignedP2PMessageResponse")
}

func init() { proto.RegisterFile("celestia/signing/v1/types.proto", fileDescriptor_1a43d868e18fb998) }

var fileDescriptor_1a43d868e18fb998 = []byte{
	// 296 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0x4d, 0x4b, 0x33, 0x31,
	0x10, 0xc7, 0x9b, 0xe7, 0xf1, 0xa5, 0x8d, 0x9e, 0x22, 0x42, 0x7d, 0x21, 0x96, 0x82, 0xd0, 0x8b,
	0x89, 0xad, 0x47, 0x6f, 0x82, 0x87, 0x0a, 0x42, 0x59, 0x6f, 0x5e, 0x24, 0xdd, 0x1d, 0xb2, 0x81,
	0x36, 0x49, 0xf3, 0xb2, 0xe0, 0xb7, 0xf0, 0x63, 0x79, 0xec, 0xd1, 0xa3, 0xb4, 0x5f, 0x44, 0x36,
	0xed, 0xd2, 0xde, 0x32, 0x33, 0xff, 0xe1, 0x97, 0xf9, 0xe1, 0x9b, 0x1c, 0x66, 0xe0, 0x83, 0x12,
	0xdc, 0x2b, 0xa9, 0x95, 0x96, 0xbc, 0x1a, 0xf2, 0xf0, 0x69, 0xc1, 0x33, 0xeb, 0x4c, 0x30, 0xe4,
	0xac, 0x09, 0xb0, 0x6d, 0x80, 0x55, 0xc3, 0x4b, 0x1a, 0x40, 0x17, 0xe0, 0xe6, 0x4a, 0x07, 0x6e,
	0x9d, 0xaa, 0x2a, 0x31, 0xdb, 0x5f, 0xea, 0xe7, 0xf8, 0xfc, 0x4d, 0x49, 0x3d, 0x19, 0x4d, 0x5e,
	0xc1, 0x7b, 0x21, 0x21, 0x83, 0x45, 0x04, 0x1f, 0x08, 0xc1, 0x07, 0xa5, 0xf0, 0x65, 0x17, 0xf5,
	0xd0, 0xe0, 0x34, 0x4b, 0x6f, 0x72, 0x81, 0xdb, 0x79, 0x29, 0x94, 0xfe, 0x50, 0x45, 0xf7, 0x5f,
	0x0f, 0x0d, 0x3a, 0xd9, 0x71, 0xaa, 0xc7, 0x05, 0xb9, 0xc2, 0x9d, 0xa8, 0xd5, 0x22, 0x42, 0x3d,
	0xfb, 0x9f, 0x66, 0xed, 0x4d, 0x63, 0x5c, 0xf4, 0x23, 0xee, 0xd6, 0x10, 0x28, 0xf6, 0x31, 0xde,
	0x1a, 0xed, 0x81, 0x5c, 0xe3, 0x4e, 0xfd, 0x5d, 0x11, 0xa2, 0x83, 0x2d, 0x6c, 0xd7, 0x20, 0x8f,
	0xf8, 0x10, 0x9c, 0x33, 0x2e, 0xe1, 0x4e, 0x46, 0xb7, 0x6c, 0x77, 0x0e, 0xdb, 0x9e, 0xc3, 0x32,
	0x98, 0x9b, 0x00, 0x09, 0xe0, 0x9e, 0xeb, 0x70, 0xb6, 0xd9, 0x79, 0x7a, 0xf9, 0x5e, 0x51, 0xb4,
	0x5c, 0x51, 0xf4, 0xbb, 0xa2, 0xe8, 0x6b, 0x4d, 0x5b, 0xcb, 0x35, 0x6d, 0xfd, 0xac, 0x69, 0xeb,
	0xfd, 0x5e, 0xaa, 0x50, 0xc6, 0x29, 0xcb, 0xcd, 0x9c, 0x37, 0xd6, 0x8c, 0x93, 0xdc, 0x8e, 0xec,
	0x5d, 0x63, 0x37, 0xf9, 0x69, 0x5c, 0x4f, 0x8f, 0x52, 0xf9, 0xf0, 0x17, 0x00, 0x00, 0xff, 0xff,
	0xfc, 0xb2, 0xcc, 0xf6, 0x86, 0x01, 0x00, 0x00,
}

func (m *SignP2PMessageRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SignP2PMessageRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SignP2PMessageRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.UniqueId) > 0 {
		i -= len(m.UniqueId)
		copy(dAtA[i:], m.UniqueId)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.UniqueId)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.ChainId) > 0 {
		i -= len(m.ChainId)
		copy(dAtA[i:], m.ChainId)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.ChainId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Hash) > 0 {
		i -= len(m.Hash)
		copy(dAtA[i:], m.Hash)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Hash)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *SignedP2PMessageResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SignedP2PMessageResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SignedP2PMessageResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Error != nil {
		{
			size, err := m.Error.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTypes(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Signature) > 0 {
		i -= len(m.Signature)
		copy(dAtA[i:], m.Signature)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Signature)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintTypes(dAtA []byte, offset int, v uint64) int {
	offset -= sovTypes(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *SignP2PMessageRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Hash)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.ChainId)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.UniqueId)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	return n
}

func (m *SignedP2PMessageResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Signature)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.Error != nil {
		l = m.Error.Size()
		n += 1 + l + sovTypes(uint64(l))
	}
	return n
}

func sovTypes(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTypes(x uint64) (n int) {
	return sovTypes(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *SignP2PMessageRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SignP2PMessageRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SignP2PMessageRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Hash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Hash = append(m.Hash[:0], dAtA[iNdEx:postIndex]...)
			if m.Hash == nil {
				m.Hash = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChainId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChainId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UniqueId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UniqueId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SignedP2PMessageResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SignedP2PMessageResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SignedP2PMessageResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signature", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signature = append(m.Signature[:0], dAtA[iNdEx:postIndex]...)
			if m.Signature == nil {
				m.Signature = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Error", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Error == nil {
				m.Error = &privval.RemoteSignerError{}
			}
			if err := m.Error.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTypes(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTypes
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTypes
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTypes
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTypes        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTypes          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTypes = fmt.Errorf("proto: unexpected end of group")
)
