name: buf-ci
on:
  push:
    branches:
      - main
      - "v[0-9]+.x"
  pull_request:
permissions:
  contents: read
  pull-requests: write
jobs:
  buf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: bufbuild/buf-setup-action@v1.50.0
      - uses: bufbuild/buf-breaking-action@v1.1.4
        with:
          against: 'https://github.com/celestiaorg/p2p-signing.git#branch=main'
      - uses: bufbuild/buf-lint-action@v1.1.1
