name: Golang Linter
on:
  push:
    branches: [main]
  pull_request:

jobs:
  golangci:
    name: golangci-lint
    runs-on: ubuntu-latest
    timeout-minutes: 8
    steps:
      - uses: actions/checkout@v4.2.2

      - uses: actions/setup-go@v5.5.0
        with:
          go-version-file: 'go.mod'

      - uses: golangci/golangci-lint-action@v6.1.0
        with:
          version: v1.61.0
          args: --timeout 10m
          github-token: ${{ secrets.github_token }}
