name: lint
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  golangci:
    name: golangci-lint
    runs-on: ubuntu-latest
    timeout-minutes: 4
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: technote-space/get-diff-action@v6.1.2
        with:
          SUFFIX_FILTER: |
            .go
            .mod
            .sum
      - uses: golangci/golangci-lint-action@v8.0.0
        with:
          version: v2.1.6
          args: --timeout 10m
        if: env.GIT_DIFF

  markdown-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: celestiaorg/.github/.github/actions/markdown-lint@main
